// The 114 surahs of the Qur'an — number, name (transliteration), englishName, ayahs, revelation type.
export interface Surah {
  number: number
  name: string
  englishName: string
  englishNameTranslation: string
  ayahs: number
  revelationType: 'Meccan' | 'Medinan'
}

export const surahs: Surah[] = [
  { number: 1, name: 'Al-Faatiha', englishName: 'The Opening', englishNameTranslation: 'The Opening', ayahs: 7, revelationType: 'Meccan' },
  { number: 2, name: 'Al-Baqara', englishName: 'The Cow', englishNameTranslation: 'The Cow', ayahs: 286, revelationType: 'Medinan' },
  { number: 3, name: 'Aal-i-Imraan', englishName: 'The Family of Imraan', englishNameTranslation: 'The Family of Imraan', ayahs: 200, revelationType: 'Medinan' },
  { number: 4, name: 'An-Nisaa', englishName: 'The Women', englishNameTranslation: 'The Women', ayahs: 176, revelationType: 'Medinan' },
  { number: 5, name: 'Al-Maaida', englishName: 'The Table', englishNameTranslation: 'The Table Spread', ayahs: 120, revelationType: 'Medinan' },
  { number: 6, name: 'Al-An\'aam', englishName: 'The Cattle', englishNameTranslation: 'The Cattle', ayahs: 165, revelationType: 'Meccan' },
  { number: 7, name: 'Al-A\'raaf', englishName: 'The Heights', englishNameTranslation: 'The Heights', ayahs: 206, revelationType: 'Meccan' },
  { number: 8, name: 'Al-Anfaal', englishName: 'The Spoils of War', englishNameTranslation: 'The Spoils of War', ayahs: 75, revelationType: 'Medinan' },
  { number: 9, name: 'At-Tawba', englishName: 'The Repentance', englishNameTranslation: 'The Repentance', ayahs: 129, revelationType: 'Medinan' },
  { number: 10, name: 'Yunus', englishName: 'Jonas', englishNameTranslation: 'Jonas', ayahs: 109, revelationType: 'Meccan' },
  { number: 11, name: 'Hud', englishName: 'Hud', englishNameTranslation: 'Hud', ayahs: 123, revelationType: 'Meccan' },
  { number: 12, name: 'Yusuf', englishName: 'Joseph', englishNameTranslation: 'Joseph', ayahs: 111, revelationType: 'Meccan' },
  { number: 13, name: 'Ar-Ra\'d', englishName: 'The Thunder', englishNameTranslation: 'The Thunder', ayahs: 43, revelationType: 'Medinan' },
  { number: 14, name: 'Ibrahim', englishName: 'Abraham', englishNameTranslation: 'Abraham', ayahs: 52, revelationType: 'Meccan' },
  { number: 15, name: 'Al-Hijr', englishName: 'The Rock', englishNameTranslation: 'The Rock', ayahs: 99, revelationType: 'Meccan' },
  { number: 16, name: 'An-Nahl', englishName: 'The Bee', englishNameTranslation: 'The Bee', ayahs: 128, revelationType: 'Meccan' },
  { number: 17, name: 'Al-Israa', englishName: 'The Night Journey', englishNameTranslation: 'The Night Journey', ayahs: 111, revelationType: 'Meccan' },
  { number: 18, name: 'Al-Kahf', englishName: 'The Cave', englishNameTranslation: 'The Cave', ayahs: 110, revelationType: 'Meccan' },
  { number: 19, name: 'Maryam', englishName: 'Mary', englishNameTranslation: 'Mary', ayahs: 98, revelationType: 'Meccan' },
  { number: 20, name: 'Taa-Haa', englishName: 'Taa-Haa', englishNameTranslation: 'Taa-Haa', ayahs: 135, revelationType: 'Meccan' },
  { number: 21, name: 'Al-Anbiyaa', englishName: 'The Prophets', englishNameTranslation: 'The Prophets', ayahs: 112, revelationType: 'Meccan' },
  { number: 22, name: 'Al-Hajj', englishName: 'The Pilgrimage', englishNameTranslation: 'The Pilgrimage', ayahs: 78, revelationType: 'Medinan' },
  { number: 23, name: 'Al-Muminoon', englishName: 'The Believers', englishNameTranslation: 'The Believers', ayahs: 118, revelationType: 'Meccan' },
  { number: 24, name: 'An-Noor', englishName: 'The Light', englishNameTranslation: 'The Light', ayahs: 64, revelationType: 'Medinan' },
  { number: 25, name: 'Al-Furqaan', englishName: 'The Criterion', englishNameTranslation: 'The Criterion', ayahs: 77, revelationType: 'Meccan' },
  { number: 26, name: 'Ash-Shu\'araa', englishName: 'The Poets', englishNameTranslation: 'The Poets', ayahs: 227, revelationType: 'Meccan' },
  { number: 27, name: 'An-Naml', englishName: 'The Ant', englishNameTranslation: 'The Ant', ayahs: 93, revelationType: 'Meccan' },
  { number: 28, name: 'Al-Qasas', englishName: 'The Stories', englishNameTranslation: 'The Stories', ayahs: 88, revelationType: 'Meccan' },
  { number: 29, name: 'Al-Ankaboot', englishName: 'The Spider', englishNameTranslation: 'The Spider', ayahs: 69, revelationType: 'Meccan' },
  { number: 30, name: 'Ar-Room', englishName: 'The Romans', englishNameTranslation: 'The Romans', ayahs: 60, revelationType: 'Meccan' },
  { number: 31, name: 'Luqman', englishName: 'Luqman', englishNameTranslation: 'Luqman', ayahs: 34, revelationType: 'Meccan' },
  { number: 32, name: 'As-Sajda', englishName: 'The Prostration', englishNameTranslation: 'The Prostration', ayahs: 30, revelationType: 'Meccan' },
  { number: 33, name: 'Al-Ahzaab', englishName: 'The Clans', englishNameTranslation: 'The Clans', ayahs: 73, revelationType: 'Medinan' },
  { number: 34, name: 'Saba', englishName: 'Sheba', englishNameTranslation: 'Sheba', ayahs: 54, revelationType: 'Meccan' },
  { number: 35, name: 'Faatir', englishName: 'The Originator', englishNameTranslation: 'The Originator', ayahs: 45, revelationType: 'Meccan' },
  { number: 36, name: 'Yaseen', englishName: 'Yaseen', englishNameTranslation: 'Yaseen', ayahs: 83, revelationType: 'Meccan' },
  { number: 37, name: 'As-Saaffaat', englishName: 'Those drawn up in Ranks', englishNameTranslation: 'Those drawn up in Ranks', ayahs: 182, revelationType: 'Meccan' },
  { number: 38, name: 'Saad', englishName: 'The letter Saad', englishNameTranslation: 'The letter Saad', ayahs: 88, revelationType: 'Meccan' },
  { number: 39, name: 'Az-Zumar', englishName: 'The Groups', englishNameTranslation: 'The Groups', ayahs: 75, revelationType: 'Meccan' },
  { number: 40, name: 'Ghaafir', englishName: 'The Forgiver', englishNameTranslation: 'The Forgiver', ayahs: 85, revelationType: 'Meccan' },
  { number: 41, name: 'Fussilat', englishName: 'Explained in detail', englishNameTranslation: 'Explained in detail', ayahs: 54, revelationType: 'Meccan' },
  { number: 42, name: 'Ash-Shura', englishName: 'Consultation', englishNameTranslation: 'Consultation', ayahs: 53, revelationType: 'Meccan' },
  { number: 43, name: 'Az-Zukhruf', englishName: 'Ornaments of gold', englishNameTranslation: 'Ornaments of gold', ayahs: 89, revelationType: 'Meccan' },
  { number: 44, name: 'Ad-Dukhaan', englishName: 'The Smoke', englishNameTranslation: 'The Smoke', ayahs: 59, revelationType: 'Meccan' },
  { number: 45, name: 'Al-Jaathiya', englishName: 'Crouching', englishNameTranslation: 'Crouching', ayahs: 37, revelationType: 'Meccan' },
  { number: 46, name: 'Al-Ahqaf', englishName: 'The Dunes', englishNameTranslation: 'The Dunes', ayahs: 35, revelationType: 'Meccan' },
  { number: 47, name: 'Muhammad', englishName: 'Muhammad', englishNameTranslation: 'Muhammad', ayahs: 38, revelationType: 'Medinan' },
  { number: 48, name: 'Al-Fath', englishName: 'The Victory', englishNameTranslation: 'The Victory', ayahs: 29, revelationType: 'Medinan' },
  { number: 49, name: 'Al-Hujuraat', englishName: 'The Inner Apartments', englishNameTranslation: 'The Inner Apartments', ayahs: 18, revelationType: 'Medinan' },
  { number: 50, name: 'Qaaf', englishName: 'The letter Qaaf', englishNameTranslation: 'The letter Qaaf', ayahs: 45, revelationType: 'Meccan' },
  { number: 51, name: 'Adh-Dhaariyat', englishName: 'The Winnowing Winds', englishNameTranslation: 'The Winnowing Winds', ayahs: 60, revelationType: 'Meccan' },
  { number: 52, name: 'At-Tur', englishName: 'The Mount', englishNameTranslation: 'The Mount', ayahs: 49, revelationType: 'Meccan' },
  { number: 53, name: 'An-Najm', englishName: 'The Star', englishNameTranslation: 'The Star', ayahs: 62, revelationType: 'Meccan' },
  { number: 54, name: 'Al-Qamar', englishName: 'The Moon', englishNameTranslation: 'The Moon', ayahs: 55, revelationType: 'Meccan' },
  { number: 55, name: 'Ar-Rahmaan', englishName: 'The Beneficent', englishNameTranslation: 'The Beneficent', ayahs: 78, revelationType: 'Medinan' },
  { number: 56, name: 'Al-Waaqia', englishName: 'The Inevitable', englishNameTranslation: 'The Inevitable', ayahs: 96, revelationType: 'Meccan' },
  { number: 57, name: 'Al-Hadid', englishName: 'The Iron', englishNameTranslation: 'The Iron', ayahs: 29, revelationType: 'Medinan' },
  { number: 58, name: 'Al-Mujaadila', englishName: 'The Pleading Woman', englishNameTranslation: 'The Pleading Woman', ayahs: 22, revelationType: 'Medinan' },
  { number: 59, name: 'Al-Hashr', englishName: 'The Exile', englishNameTranslation: 'The Exile', ayahs: 24, revelationType: 'Medinan' },
  { number: 60, name: 'Al-Mumtahana', englishName: 'She that is to be examined', englishNameTranslation: 'She that is to be examined', ayahs: 13, revelationType: 'Medinan' },
  { number: 61, name: 'As-Saff', englishName: 'The Ranks', englishNameTranslation: 'The Ranks', ayahs: 14, revelationType: 'Medinan' },
  { number: 62, name: 'Al-Jumua', englishName: 'The Congregation, Friday', englishNameTranslation: 'The Congregation, Friday', ayahs: 11, revelationType: 'Medinan' },
  { number: 63, name: 'Al-Munaafiqoon', englishName: 'The Hypocrites', englishNameTranslation: 'The Hypocrites', ayahs: 11, revelationType: 'Medinan' },
  { number: 64, name: 'At-Taghaabun', englishName: 'Mutual Disillusion', englishNameTranslation: 'Mutual Disillusion', ayahs: 18, revelationType: 'Medinan' },
  { number: 65, name: 'At-Talaaq', englishName: 'Divorce', englishNameTranslation: 'Divorce', ayahs: 12, revelationType: 'Medinan' },
  { number: 66, name: 'At-Tahrim', englishName: 'The Prohibition', englishNameTranslation: 'The Prohibition', ayahs: 12, revelationType: 'Medinan' },
  { number: 67, name: 'Al-Mulk', englishName: 'The Sovereignty', englishNameTranslation: 'The Sovereignty', ayahs: 30, revelationType: 'Meccan' },
  { number: 68, name: 'Al-Qalam', englishName: 'The Pen', englishNameTranslation: 'The Pen', ayahs: 52, revelationType: 'Meccan' },
  { number: 69, name: 'Al-Haaqqa', englishName: 'The Reality', englishNameTranslation: 'The Reality', ayahs: 52, revelationType: 'Meccan' },
  { number: 70, name: 'Al-Ma\'aarij', englishName: 'The Ascending Stairways', englishNameTranslation: 'The Ascending Stairways', ayahs: 44, revelationType: 'Meccan' },
  { number: 71, name: 'Nooh', englishName: 'Noah', englishNameTranslation: 'Noah', ayahs: 28, revelationType: 'Meccan' },
  { number: 72, name: 'Al-Jinn', englishName: 'The Jinn', englishNameTranslation: 'The Jinn', ayahs: 28, revelationType: 'Meccan' },
  { number: 73, name: 'Al-Muzzammil', englishName: 'The Enshrouded One', englishNameTranslation: 'The Enshrouded One', ayahs: 20, revelationType: 'Meccan' },
  { number: 74, name: 'Al-Muddaththir', englishName: 'The Cloaked One', englishNameTranslation: 'The Cloaked One', ayahs: 56, revelationType: 'Meccan' },
  { number: 75, name: 'Al-Qiyaama', englishName: 'The Resurrection', englishNameTranslation: 'The Resurrection', ayahs: 40, revelationType: 'Meccan' },
  { number: 76, name: 'Al-Insaan', englishName: 'The Man', englishNameTranslation: 'The Man', ayahs: 31, revelationType: 'Medinan' },
  { number: 77, name: 'Al-Mursalaat', englishName: 'The Emissaries', englishNameTranslation: 'The Emissaries', ayahs: 50, revelationType: 'Meccan' },
  { number: 78, name: 'An-Naba', englishName: 'The Announcement', englishNameTranslation: 'The Announcement', ayahs: 40, revelationType: 'Meccan' },
  { number: 79, name: 'An-Naazi\'aat', englishName: 'Those who drag forth', englishNameTranslation: 'Those who drag forth', ayahs: 46, revelationType: 'Meccan' },
  { number: 80, name: 'Abasa', englishName: 'He frowned', englishNameTranslation: 'He frowned', ayahs: 42, revelationType: 'Meccan' },
  { number: 81, name: 'At-Takwir', englishName: 'The Overthrowing', englishNameTranslation: 'The Overthrowing', ayahs: 29, revelationType: 'Meccan' },
  { number: 82, name: 'Al-Infitaar', englishName: 'The Cleaving', englishNameTranslation: 'The Cleaving', ayahs: 19, revelationType: 'Meccan' },
  { number: 83, name: 'Al-Mutaffifin', englishName: 'The Defrauding', englishNameTranslation: 'The Defrauding', ayahs: 36, revelationType: 'Meccan' },
  { number: 84, name: 'Al-Inshiqaaq', englishName: 'The Splitting Open', englishNameTranslation: 'The Splitting Open', ayahs: 25, revelationType: 'Meccan' },
  { number: 85, name: 'Al-Burooj', englishName: 'The Constellations', englishNameTranslation: 'The Constellations', ayahs: 22, revelationType: 'Meccan' },
  { number: 86, name: 'At-Taariq', englishName: 'The Morning Star', englishNameTranslation: 'The Morning Star', ayahs: 17, revelationType: 'Meccan' },
  { number: 87, name: 'Al-A\'laa', englishName: 'The Most High', englishNameTranslation: 'The Most High', ayahs: 19, revelationType: 'Meccan' },
  { number: 88, name: 'Al-Ghaashiya', englishName: 'The Overwhelming', englishNameTranslation: 'The Overwhelming', ayahs: 26, revelationType: 'Meccan' },
  { number: 89, name: 'Al-Fajr', englishName: 'The Dawn', englishNameTranslation: 'The Dawn', ayahs: 30, revelationType: 'Meccan' },
  { number: 90, name: 'Al-Balad', englishName: 'The City', englishNameTranslation: 'The City', ayahs: 20, revelationType: 'Meccan' },
  { number: 91, name: 'Ash-Shams', englishName: 'The Sun', englishNameTranslation: 'The Sun', ayahs: 15, revelationType: 'Meccan' },
  { number: 92, name: 'Al-Lail', englishName: 'The Night', englishNameTranslation: 'The Night', ayahs: 21, revelationType: 'Meccan' },
  { number: 93, name: 'Ad-Dhuhaa', englishName: 'The Morning Hours', englishNameTranslation: 'The Morning Hours', ayahs: 11, revelationType: 'Meccan' },
  { number: 94, name: 'Ash-Sharh', englishName: 'The Relief', englishNameTranslation: 'The Relief', ayahs: 8, revelationType: 'Meccan' },
  { number: 95, name: 'At-Tin', englishName: 'The Fig', englishNameTranslation: 'The Fig', ayahs: 8, revelationType: 'Meccan' },
  { number: 96, name: 'Al-Alaq', englishName: 'The Clot', englishNameTranslation: 'The Clot', ayahs: 19, revelationType: 'Meccan' },
  { number: 97, name: 'Al-Qadr', englishName: 'The Power', englishNameTranslation: 'The Power', ayahs: 5, revelationType: 'Meccan' },
  { number: 98, name: 'Al-Bayyina', englishName: 'The Clear Proof', englishNameTranslation: 'The Clear Proof', ayahs: 8, revelationType: 'Medinan' },
  { number: 99, name: 'Az-Zalzala', englishName: 'The Earthquake', englishNameTranslation: 'The Earthquake', ayahs: 8, revelationType: 'Medinan' },
  { number: 100, name: 'Al-Aadiyaat', englishName: 'The Chargers', englishNameTranslation: 'The Chargers', ayahs: 11, revelationType: 'Meccan' },
  { number: 101, name: 'Al-Qaari\'a', englishName: 'The Calamity', englishNameTranslation: 'The Calamity', ayahs: 11, revelationType: 'Meccan' },
  { number: 102, name: 'At-Takaathur', englishName: 'Competition', englishNameTranslation: 'Competition', ayahs: 8, revelationType: 'Meccan' },
  { number: 103, name: 'Al-Asr', englishName: 'The Declining Day', englishNameTranslation: 'The Declining Day', ayahs: 3, revelationType: 'Meccan' },
  { number: 104, name: 'Al-Humaza', englishName: 'The Traducer', englishNameTranslation: 'The Traducer', ayahs: 9, revelationType: 'Meccan' },
  { number: 105, name: 'Al-Fil', englishName: 'The Elephant', englishNameTranslation: 'The Elephant', ayahs: 5, revelationType: 'Meccan' },
  { number: 106, name: 'Quraish', englishName: 'Quraysh', englishNameTranslation: 'Quraysh', ayahs: 4, revelationType: 'Meccan' },
  { number: 107, name: 'Al-Maa\'un', englishName: 'The Small Kindnesses', englishNameTranslation: 'The Small Kindnesses', ayahs: 7, revelationType: 'Meccan' },
  { number: 108, name: 'Al-Kawthar', englishName: 'The Abundance', englishNameTranslation: 'The Abundance', ayahs: 3, revelationType: 'Meccan' },
  { number: 109, name: 'Al-Kaafiroon', englishName: 'The Disbelievers', englishNameTranslation: 'The Disbelievers', ayahs: 6, revelationType: 'Meccan' },
  { number: 110, name: 'An-Nasr', englishName: 'The Divine Support', englishNameTranslation: 'The Divine Support', ayahs: 3, revelationType: 'Medinan' },
  { number: 111, name: 'Al-Masad', englishName: 'The Palm Fiber', englishNameTranslation: 'The Palm Fiber', ayahs: 5, revelationType: 'Meccan' },
  { number: 112, name: 'Al-Ikhlaas', englishName: 'The Sincerity', englishNameTranslation: 'The Sincerity', ayahs: 4, revelationType: 'Meccan' },
  { number: 113, name: 'Al-Falaq', englishName: 'The Daybreak', englishNameTranslation: 'The Daybreak', ayahs: 5, revelationType: 'Meccan' },
  { number: 114, name: 'An-Naas', englishName: 'The Mankind', englishNameTranslation: 'The Mankind', ayahs: 6, revelationType: 'Meccan' },
]
